pipeline {
    agent any
    stages {
        stage('Debug Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
                sh 'ls -la ..'
                sh 'find .. -type d | grep -v "\.git" | sort'
            }
        }
        // ... rest of your stages
    }
}